dataset: data/raw.csv

preprocessing:
  scale: True
  encode: False

model:
  type: RandomForestClassifier
  params:
    n_estimators: 200
    max_depth: 7
    random_state: 42

training:
  test_size: 0.2
  random_state: 42
